### ISSUE TITLE
Internal Server error after trying to load opportunities for new project

### ISSUE THREAD

**Issue by mlbtc** [transitcenter/tesca#4]
Getting this error after trying to use an opportunities.csv files 

<img width="1152" alt="image" src="https://github.com/transitcenter/tesca/assets/84036764/edb4018e-df70-4613-bd0d-4d299aa9757b">

It's for the Philly analysis - it's the same opportunities file that we originally used but I added two new columns for additional opportunity types

**Comment by wklumpen** [comment]
I believe this one is fixed right - this was caused by the text of the block group ID columns being formatted into scientific notation by Excel?
